baseurl = "/"
languageCode = "en-us"
title = "madrug -- Madison R User Group"
theme = "hugo-theme-basic"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/orgs/madisonrug/"

# basic theme

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = ""
  
[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

#[[params.menu]]
#  name = "post series"
#  url = "series/"
  
[[params.menu]]
  name = "upcoming events"
  url = "upcoming-events/"


[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true